### ISSUE TITLE
NeoDen "Daniel" setup

### ISSUE THREAD

**Issue by mateusz-spychala** [Aerobits/openpnp#13]

**Comment by CezaryPuchowski** [comment]
Speed powyżej 60% może powodować problemy z homowaniem na fiducialu

**Comment by CezaryPuchowski** [comment]
Niesprawny krokowiec od rotacji nozzla nr 4.

**Comment by CezaryPuchowski** [comment]
Krokowiec naprawiony.

NeoDen gotowy do zainstalowania na górze. 
Podobno w poniedziałek będzie sens go tam wnosić.
