### ISSUE TITLE
Automatyczna zmiana nozli

### ISSUE THREAD

**Issue by mateusz-spychala** [Aerobits/openpnp#4]
https://www.youtube.com/watch?v=hiDLxEOzHfw
https://www.youtube.com/watch?app=desktop&v=qcL0MLGex4M

Actuators:
https://rcmaniak.pl/pl/p/Serwo-2.9g-liniowe-szybkie-na-ogon/1742

Tuleje i wałki:
https://www.albeco.com.pl/pl/produkt/3A2E/tuleja-samosmarna-spiekana-a-3-6-4-ames.html

inne:
https://botland.com.pl/sterowniki-serw/67-sterownik-serw-micro-maestro-usb-6-kanalowy-pololu-1350-5904422367893.html
https://botland.com.pl/przetwornice-step-up-step-down/1255-s7v8a-przetwornica-step-upstep-down-25-8v-1a-pololu-2118-5904422305758.html

**Comment by CezaryPuchowski** [comment]
https://modelarski.bialystok.pl/297-prety-weglowe?q=Dost%C4%99pno%C5%9B%C4%87-W+magazynie

**Comment by CezaryPuchowski** [comment]
Ogólnie mamy sobie NozzleChanger ale sterujemy nim po serialu.
W OpenPnP jest interpreter pythona zgodny z Java który nazywa się Jython i jest obecnie w wersji 2.7 (tak, odpowiada to pythonowi 2.7)
W ustawieniach OpenPnP nie da się raczej dodać aktuatora po serialu z marszu, lub jakiegoś innego drivera/kontrolera dla NozzleChangera.
Jython 2.7 nie umie współpracować z serialem, albo jeszcze nie wiem jak to zrobić aby umiał.
Wiec chyba najprościej (dla znającego Javę) było by napisanie obługi NozzleChangera w Javie bezpośrednio. I tak mamy własną wersję na własnej branczy tego całego OpenPnP

Jakiś pomysł w którą stronę iść?

**Comment by mateusz-spychala** [comment]
Nie da się drugiego drivera dodać serialowego?

**Comment by CezaryPuchowski** [comment]
No niby da, ale typowo Neodenowy, czyli OpenPnP chce feedbacku z wszystkich akcji które wykonuje.
Można dodać Gcodowy Driver ale ten znowu raczej będzie dostawał chyba wszystkie Gcody z ruchów maszyną, nie wiem czy to ta droga którą chcemy iść i nie wiem jak zrobić aby wśród tych kodów wysyłać takie które odpowiadają ruchom dla NozzleChangera

**Comment by mateusz-spychala** [comment]
Wydaje mi się że się da.

**Comment by mateusz-spychala** [comment]
https://github.com/openpnp/openpnp/wiki/Setup-and-Calibration_Actuators

można pod aktuator driver podpiąć

**Comment by mateusz-spychala** [comment]
Popatrz na to ok?
https://github.com/openpnp/openpnp/wiki/GcodeDriver#sub-drivers

**Comment by mateusz-spychala** [comment]
Już w miarę przedyskutowane to jest.

**Comment by mateusz-spychala** [comment]
Przy 3 neodenach można nozle na stałe zamontować
